update
Signed-off-by: Chris Lyons <52037738+mephmanx@users.noreply.github.com>

diff --git a/manifests/06-kie-server.yaml b/manifests/06-kie-server.yaml
--- a/manifests/06-kie-server.yaml
+++ b/manifests/06-kie-server.yaml
@@ -777,7 +777,7 @@ spec:
                 killall -s TERM linkerd-proxy >/dev/null 2>&1 || true
                 killall -s TERM linkerd2-proxy >/dev/null 2>&1 || true
               }
-              trap cleanup_proxy EXIT
+              # trap cleanup_proxy EXIT
               if [ ! -f /vault-secrets/kie-users-env.sh ]; then
                 echo "ERROR: KIE credentials not found"
                 exit 1
